feauture-implemented-interaction-api
n4x15/my-favourite-movies-frontend pull request #6
Opened 2022-03-02 12:47 UTC by n4x15

2022-03-02 13:06 UTC, k41n requested changes
Чини

2022-03-02 13:06 UTC, k41n commented on src/Utils.tsx
> +    `${url}${movies}?api_key=${process.env.REACT_APP_API_KEY}&language=${language}
Так замучаешься поддерживать, лучше явно отмапать:
```
interface GetMoviesArgs {
  language?: string;
  with_genres?: string;
  without_genres?: string;
  year?: number;
  rating?: number;
}

const mapArgsToApi = (filters: GetMoviesArgs): string => Object.entries({
    api_key: process.env.REACT_APP_API_KEY,
    ...filters,
    ...(filters.rating ? { 'vote_average.gte': `${filters.rating}` } : {}),
    page: 1,
  })
    .map(([key, val]) => `${key}=${val}`)
    .join('&');

export const getMovies = async (filters: GetMoviesArgs) => {
  const effectiveUrl = `${url}${movies}?${mapArgsToApi(filters)}`;
  const response = await axios.get(effectiveUrl);
  return response.data.results;
};
```

2022-03-02 13:06 UTC, k41n commented on package.json
> +    "axios": "^0.26.0",
А зачем нужен axios, мы же на фронте, у нас есть нативный fetch?

2022-03-03 11:11 UTC, reshetov commented on package.json
> +    "axios": "^0.26.0",
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

2022-03-03 11:12 UTC, reshetov commented on src/Utils.tsx
> +  try {
1. Переключись на fetch https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
2. У fetch и axios есть свои catch, стандартный тут излишен

2022-03-03 13:25 UTC, merged