feature-implemented-AddMoviePage
n4x15/my-favourite-movies-frontend pull request #8
Opened 2022-03-23 09:46 UTC by n4x15

2022-03-23 14:01 UTC, Isidora25 requested changes

2022-03-25 11:58 UTC, n4x15 commented on src/components/AddPage/AddMoviePage.tsx
> +        (movie: IMovie) => (movie.isSaved = saved.indexOf(movie.id) >= 0)
Свойству isSaved присваивается true|false для отображения уже сохраненных фильмов в поиске

2022-03-25 12:14 UTC, Isidora25 commented on src/components/AddPage/AddMoviePage.tsx
> +        (movie: IMovie) => (movie.isSaved = saved.indexOf(movie.id) >= 0)
Ок, принято

2022-03-25 13:04 UTC, Isidora25 commented on src/components/AddPage/utils/utils.ts
> +export const yearsArray = [1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008
А куда делся маппинг?)
А если начала периода будет в 1900?)

2022-03-25 13:04 UTC, Isidora25 commented on src/components/MainPage/components/FavoriteMovies/FavoriteMovies.tsx
> +      movie.id === id ? (movie.isWatched = !movie.isWatched) : false
Тоже самое, if или &&

2022-03-25 13:04 UTC, Isidora25 commented on src/hooks/useGenres.ts
> +  const handleGenres = (index: number, id: number) => {
тут тоже индексы нужно убрать

2022-03-25 14:09 UTC, merged